name: Build and push image
on:
  push:
    tags:
      - '*'
      - '!flux-*'
jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    container:
      image: thomasweise/docker-texlive-full:latest
    steps:
      - uses: actions/checkout@v2

      - name: install jsonnet
        run: ./scripts/install_jsonnet.sh

      - name: install git and pipenv
        run: |
          apt-get update
          apt-get install -y git python3 python3-pip

      - name: install pipenv
        run: pip3 install pipenv

      - name: build
        run: make docker

      - name: push
        env: 
          GKEY: ${{secrets.GOOGLE_KEY}}

        run: |
          # fixme - get the hostname from the registry name
          echo "$GKEY" | docker login -u _json_key --password-stdin https://eu.gcr.io
          make push
