name: Build and push image
on:
  push:
    tags:
      - '*'
      - '!flux-*'

jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        

      - name: build
        env:
          GIT_SHA: ${{ github.sha }}
          GIT_TAG: ${{ steps/get_version.outputs.version }}

        run: make docker

      - name: push
        env: 
          GKEY: ${{secrets.GOOGLE_KEY}}

        run: |
          # fixme - get the hostname from the registry name
          echo "$GKEY" | docker login -u _json_key --password-stdin https://eu.gcr.io
          make push
